### PR TITLE
[PM-2901] Synchronize sends on send creation/update/deletion notification

### LINKED ISSUE #2571: Sends not syncing automatically on mobile
### Steps To Reproduce

1. Sign into Bitwarden on a mobile device and go to the Sends tab
2. Sign into Bitwarden on another device and create a send

### Expected Result

The send should appear after a few seconds.

### Actual Result

The send only appears when manually doing a full sync of the vault.

### Screenshots or Videos

_No response_

### Additional Context

As far as I can tell this is due to 
```
SyncSendCreate = 12,
SyncSendUpdate = 13,
SyncSendDelete = 14,
```

not being implemented here: https://github.com/bitwarden/mobile/blob/98705e443f321411dd3b7c8d54581fe4462cc3c5/src/App/Services/PushNotificationListenerService.cs#L76-L162

### Operating System

Android, iOS

### Operating System Version

_No response_

### Device

iPad Pro 2020, Xiaomi Mi9T-Pro

### Build Version

2023.5.0

### Beta

- [ ] Using a pre-release version of the application.

### PR DESCRIPTION
**Pull request by quexten**
## Type of change
- [x] Bug fix
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] New feature development
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Fixes #2571. On desktop/web, sends are synced when the Websocket notification notifying the clients of the creation/update/deletion arrives. On mobile this is not implemented. This PR brings feature parity in that regard by implementing syncing send creation/updates/deletions on arrival of the Firebase notification.

Beware, I was not able to fully test this as the default config builds for the QA push environment.

## Code changes

* PushNotificationListenerService.cs Add code handling the 3 send notification types (creation, update, deletion). The code is pretty much the same as for ciphers.
* NotificationResponse.cs Add a class to contain send sync notification data
* ISyncService.cs, SyncService.cs Add code for doing a sync for sends.

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

File: src/App/Services/PushNotificationListenerService.cs [hunk 1]
```diff
@@ -131,6 +131,24 @@ public async Task OnMessageAsync(JObject value, string deviceType)
...
                     }
                     break;
+                case NotificationType.SyncSendCreate:
+                case NotificationType.SyncSendUpdate:
+                    var sendCreateUpdateMessage = JsonConvert.DeserializeObject<SyncSendNotification>(
+                        notification.Payload);
+                    if (isAuthenticated && sendCreateUpdateMessage.UserId == myUserId)
+                    {
+                        await _syncService.Value.SyncUpsertSendAsync(sendCreateUpdateMessage,
+                            notification.Type == NotificationType.SyncCipherUpdate);
```
Comment (aj-rosado) [inline src/App/Services/PushNotificationListenerService.cs:141]:
```suggestion
                            notification.Type == NotificationType.SyncSendUpdate);
```
Should be `NotificationType.SyncSendUpdate` instead `NotificationType.SyncCipherUpdate`

File: src/Core/Services/SyncService.cs [hunk 2]
```diff
@@ -274,6 +274,78 @@ public async Task<bool> SyncDeleteCipherAsync(SyncCipherNotification notificatio
             return SyncCompleted(false);
         }
 
+        public async Task<bool> SyncUpsertSendAsync(SyncSendNotification notification, bool isEdit)
+        {
+            SyncStarted();
+            if (await _stateService.IsAuthenticatedAsync())
```
Comment (aj-rosado) [inline src/Core/Services/SyncService.cs:280]: Could you please invert this if to avoid nesting and improve reability?

File: src/Core/Services/SyncService.cs [hunk 3]
```diff
@@ -274,6 +274,78 @@ public async Task<bool> SyncDeleteCipherAsync(SyncCipherNotification notificatio
...
+            {
+                try
+                {
+                    var shouldUpdate = true;
```
Comment (aj-rosado) [inline src/Core/Services/SyncService.cs:284]: This `shouldUpdate` isn't really necessary, we can just `return SyncCompleted(false);` when we don't need to update the code also reducing the number of ifs in this method

**Review by aj-rosado — CHANGES_REQUESTED** [review]
Thank you for your contribution @quexten , I really appreciate your work on this

I'd like to request a minor adjustment in the notification type validation.

While the code follows Cipher's logic, I also have a few suggestions to further enhance readability and reduce indentation. If you could implement these changes, I would be sincerely grateful! 😃

File: src/Core/Services/SyncService.cs (hunk 3 above)
Comment (quexten) [reply src/Core/Services/SyncService.cs]: I simplified this in 743bf06b24514459a236efd43fa9e297948ed8f9. Let me know if this addresses your change request :)

**Review by aj-rosado — CHANGES_REQUESTED** [review]
Thank you for your efforts cleaning the code 👏 

Just requesting two more changes.

File: src/Core/Services/SyncService.cs [hunk 4]
```diff
@@ -274,6 +274,65 @@ public async Task<bool> SyncDeleteCipherAsync(SyncCipherNotification notificatio
             return SyncCompleted(false);
         }
 
+        public async Task<bool> SyncUpsertSendAsync(SyncSendNotification notification, bool isEdit)
+        {
+            SyncStarted();
+            if (!await _stateService.IsAuthenticatedAsync()) return SyncCompleted(false);
```
[the remark this answers is not in the document]
Comment (quexten) [reply src/Core/Services/SyncService.cs]: Done.

File: src/Core/Services/SyncService.cs [hunk 5]
```diff
@@ -274,6 +274,65 @@ public async Task<bool> SyncDeleteCipherAsync(SyncCipherNotification notificatio
...
+            try
+            {
+                var localSend = await _sendService.GetAsync(notification.Id);
+                if (localSend != null && localSend.RevisionDate >= notification.RevisionDate)
+                {
+                    if ((isEdit && localSend == null) || (!isEdit && localSend != null))
+                    {
+                        return SyncCompleted(false);
+                    }
+                }
```
[the remark this answers is not in the document]
Comment (quexten) [reply src/Core/Services/SyncService.cs]: Done.

File: src/Core/Services/SyncService.cs [hunk 6]
```diff
@@ -274,6 +274,66 @@ public async Task<bool> SyncDeleteCipherAsync(SyncCipherNotification notificatio
...
+            if (!await _stateService.IsAuthenticatedAsync())
+            {
+                return SyncCompleted(false);
+            }
+
+            try
+            {
+                var localSend = await _sendService.GetAsync(notification.Id);
+                if (localSend != null && localSend.RevisionDate >= notification.RevisionDate
+                    && ((isEdit && localSend == null) || (!isEdit && localSend != null)))
```
Comment (aj-rosado) [inline src/Core/Services/SyncService.cs:289]:
```suggestion
                if ((localSend != null && localSend.RevisionDate >= notification.RevisionDate)
                    || (isEdit && localSend == null) || (!isEdit && localSend != null))
```

I think the if should be like this. Thank you for taking your time making this changes. I really appreciate it

**Review by aj-rosado — DISMISSED** [review]
Looking good! Thank you for your contribution and the efforts in improving it.

Sending to QA 🎉

**Review by aj-rosado — APPROVED** [review]
Reapproving it, just committed a minor fix on whitespace.

**Comment by aj-rosado** [comment]
Thank you for your contribution! This has been merged and will be part of a future release! 🎉 🥳
